name: calorize
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.2
  fl_chart: ^1.1.1
  flutter_native_splash: ^2.4.7
  permission_handler: ^12.0.1
  home_widget: ^0.8.1
  shared_preferences: ^2.5.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  intl: ^0.18.1
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2
  openfoodfacts: ^3.1.0
  google_generative_ai: ^0.4.7
  camera: ^0.11.3
  http: ^1.2.2
  provider: ^6.1.2
  url_launcher: ^6.3.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_timezone: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
